# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OfflineBarExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OfflineBarExample
  pod 'OfflineBar', :git => '../../.git'
  
  target 'OfflineBarExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OfflineBarExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
